include: package:very_good_analysis/analysis_options.2.4.0.yaml
linter:
  rules:
    public_member_api_docs: false
    use_key_in_widget_constructors: false
    sort_pub_dependencies: false
    always_use_package_imports: false
    flutter_style_todos: false
    avoid_setters_without_getters: false
