name: {{project_name}}
description: {{project_description.sentenceCase()}}
version: 1.0.4+2
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  api_controller:
    path: packages/api_controller
  app_ui:
    path: packages/app_ui

  bloc: ^7.2.1
  equatable: ^2.0.3
  firebase_core: ^1.3.0
  firebase_messaging: ^11.1.0
  flutter_local_notifications: ^9.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  webview_flutter: ^2.3.1
  connectivity_plus: ^2.2.1
  provider: ^6.0.2



dev_dependencies:
  bloc_test: ^8.4.0
  flutter_test:
    sdk: flutter
  glob: ^2.0.1
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0
  dartz: ^0.10.0-nullsafety.2

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Inter
      fonts:
        - asset: packages/app_ui/assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: packages/app_ui/assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: packages/app_ui/assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: packages/app_ui/assets/fonts/Inter-Bold.ttf
          weight: 700

