name: app_ui
description: UI Toolkit for the {{project_name}} app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0-alpha.1
  dots_indicator: ^2.0.0
  flutter:
    sdk: flutter

  flutter_staggered_grid_view: ^0.6.0
  flutter_svg: ^0.23.0+1 #svg support in the app
  flutter_widget_from_html_core: ^0.8.5+3
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0 #Shimmer loading
  timeago: ^3.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  very_good_analysis: ^2.4.0

flutter:

  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/

